[workspace]

members= [
    "crates/forge",
    "crates/forger",
    "crates/argparser",
    "crates/cli",
    "crates/commander",
    "crates/constants",
    "crates/filehandler",
    "crates/forger",
    "crates/interpreter",
    "crates/logger",
    "crates/parser",
    "crates/variable"
]